/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import { getFileLicense } from './license';
import { iLog } from './log';
import { generateBlocks } from './tables/blocks';
import { generateCaseFoldMappings, generateCaseFoldSimpleMappings, generateSimpleCaseMappings, generateSpecialCaseMappings } from './tables/case';
import { generateCollationContractions, generateCollationEntries } from './tables/collation';
import { generateDecompositionAndCompositionTables } from './tables/composition';
import { generateConfusables } from './tables/confusable';
import { generateEmoji } from './tables/emoji';
import { generateNCharacters } from './tables/n-characters';
import { generateNames } from './tables/names';
import { generateNumericValues } from './tables/numeric';
import { generateProperties } from './tables/properties';
import { generateScriptExtensions } from './tables/script-extensions';
import { getUnicodeTableData, UnicodeTableData } from './unicode-data-store';

// Writes the generated Unicode C tables from the in-memory generation data.
export async function generateUnicodeTables(data: UnicodeTableData = getUnicodeTableData()) {
  iLog('Generate Unicode tables');

  const outputPath = resolve(__dirname, '../../src/unicode-data.h');
  const output = `${getFileLicense()}

// This file is automatically generated. Do not edit.
// clang-format off

#include <stddef.h>
#include <string.h>

#include "unicode-tables.h"

${generateBlocks(data.blocks)}
${generateNames(data.prefixes, data.names)}
${generateEmoji(data.emoji, data.emojiSequences)}
${generateProperties(data.properties)}
${generateScriptExtensions(data.scriptExtensions)}
${generateNCharacters(data.nCharacters)}
${generateDecompositionAndCompositionTables(data.decompositions,
  data.compatibilityDecompositions, data.compositions)}
${generateNumericValues(data.numericValues)}
${generateSimpleCaseMappings(data.simpleCaseMappings)}
${generateSpecialCaseMappings(data.specialCaseMappings)}
${generateCaseFoldMappings(data.caseFoldMappings)}
${generateCaseFoldSimpleMappings(data.caseFoldSimpleMappings)}
${generateConfusables(data.confusables)}
${generateCollationEntries(data.collationEntries)}
${generateCollationContractions(data.collationContractions)}// clang-format on
`;

  await writeFile(outputPath, output);
}
