/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';
import functions from './functions';
import { getFileLicense } from './license';
import { iLog } from './log';

function typeMap(type: string) {
  if(type.includes('*')) {
    return 'Pointer';
  } else if(type === 'bool') {
    return 'boolean';
  } else if(type === 'mjb_codepoint') {
    return 'Codepoint';
  }

  return 'number';
}

function functionList() {
  let output: string[] = [];

  for(const func of functions) {
    if(!func.wasm) {
      continue;
    }

    const args = func.args.map((arg) => {
      return `${arg.name}: ${typeMap(arg.type)}`;
    }).join(', ');

    output.push(`  // ${func.comment}
  _mjb_${func.name}: (${args}) => ${typeMap(func.ret)};`);
  }

  return output.join('\n');
}

export function generateWasmTD() {
  iLog('Generate mojibake.d.ts');

  const outputPath = resolve(__dirname, '../../src/api/mojibake.d.ts');
  const output = `${getFileLicense()}

// This file is automatically generated. Do not edit.

export type Pointer = number;
export type Codepoint = number;

export type MojibakeWasmModule = {
  HEAPU8: Uint8Array;
  HEAP32: Int32Array;
  ccall: (
    ident: string,
    returnType?: string | null,
    argTypes?: string[],
    args?: unknown[]
  ) => unknown;
  cwrap: (ident: string, returnType?: string | null, argTypes?: string[]) => unknown;
  _malloc: (size: number) => number;
  _free: (ptr: number) => void;
${functionList()}
};

export default function mojibakeModule(): Promise<MojibakeWasmModule>;`;

  writeFileSync(outputPath, output);
}
