/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

import { createReadStream, createWriteStream } from 'fs';
import { resolve } from 'path';

export async function generateEmbeddedDB() {
  let length = 0;
  const dbPath = resolve(__dirname, '../../mojibake.db');
  const headerPath = resolve(__dirname, '../../src/embedded-db.h');

  const reader = createReadStream(dbPath);
  const writer = createWriteStream(headerPath);

  const header = `/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

#pragma once

#ifndef MJB_EMBEDDED_DB_H
#define MJB_EMBEDDED_DB_H

// This file is automatically generated. Do not edit.

#ifdef __cplusplus
extern "C" {
#endif

static const unsigned char mjb_db_embedded[] = {
`;

  writer.write(header);

  let first = true;

  for await (const chunk of reader) {
    for(const byte of chunk) {
      if(first) {
        first = false;
      } else {
        writer.write(',');
      }

      ++length;
      writer.write(byte.toString());

      if(length % 50 === 0) {
        writer.write('\n');
      }
    }
  }

  const footer = `};

static const unsigned int mjb_db_embedded_len = ${length};

#ifdef __cplusplus
}
#endif

#endif // MJB_EMBEDDED_DB_H\n`;

  writer.write(footer);
  writer.end();

  return new Promise<void>((resolve, reject) => {
    writer.on('finish', resolve);
    writer.on('error', reject);
  });
}
