/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

export async function generateEmbeddedDB() {
  let length = 0;
  const file = Bun.file('../../mojibake.db');
  const reader = file.stream().getReader();
  const writer = Bun.file('../../src/embedded-db.h').writer();

  writer.write(`/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

#pragma once

#ifndef MJB_EMBEDDED_DB_H
#define MJB_EMBEDDED_DB_H

// This file is automatically generated. Do not edit.

#ifdef __cplusplus
extern "C" {
#endif

static const unsigned char mjb_db_embedded[] = {\n`);

  let first = true;

  while(true) {
    const { value: chunk, done } = await reader.read();

    for(const byte of chunk ?? []) {
      if(first) {
        first = false;
      } else {
        writer.write(',');
      }

      ++length;
      writer.write(byte.toString());

      if(length % 50 === 0) {
        writer.write('\n');
      }
    }

    if(done) {
      break;
    }
  }

  writer.write(`};

static const unsigned int mjb_db_embedded_len = ${length};

#ifdef __cplusplus
}
#endif

#endif // MJB_EMBEDDED_DB_H\n`);
}
