#!/bin/sh

SQLITE_VERSION="3500200"
SQLITE_YEAR="2025"

if [ ! -d "./sqlite-src-$SQLITE_VERSION" ] ; then
    curl -o sqlite3.zip "https://www.sqlite.org/$SQLITE_YEAR/sqlite-src-$SQLITE_VERSION.zip"
    unzip sqlite3.zip
fi

cd sqlite-src-$SQLITE_VERSION

if [ ! -f "Makefile" ]; then
    cp Makefile.linux-generic Makefile
fi

make clean

OPTS="-DSQLITE_OMIT_ALTERTABLE \
-DSQLITE_OMIT_ANALYZE \
-DSQLITE_OMIT_AUTHORIZATION \
-DSQLITE_OMIT_AUTOINCREMENT \
-DSQLITE_OMIT_AUTOINIT \
-DSQLITE_OMIT_BLOB_LITERAL \
-DSQLITE_OMIT_CASE_SENSITIVE_LIKE_PRAGMA \
-DSQLITE_OMIT_CHECK \
-DSQLITE_OMIT_COMPILEOPTION_DIAGS \
-DSQLITE_OMIT_COMPLETE \
-DSQLITE_OMIT_COMPOUND_SELECT \
-DSQLITE_OMIT_DECLTYPE \
-DSQLITE_OMIT_DEPRECATED \
-DSQLITE_OMIT_DESERIALIZE \
-DSQLITE_OMIT_EXPLAIN \
-DSQLITE_OMIT_FLAG_PRAGMAS \
-DSQLITE_OMIT_FOREIGN_KEY \
-DSQLITE_OMIT_GENERATED_COLUMNS \
-DSQLITE_OMIT_GET_TABLE \
-DSQLITE_OMIT_INCRBLOB \
-DSQLITE_OMIT_INTEGRITY_CHECK \
-DSQLITE_OMIT_INTROSPECTION_PRAGMAS \
-DSQLITE_OMIT_JSON \
-DSQLITE_OMIT_LOAD_EXTENSION \
-DSQLITE_OMIT_LOCALTIME \
-DSQLITE_OMIT_MEMORYDB \
-DSQLITE_OMIT_PROGRESS_CALLBACK \
-DSQLITE_OMIT_REINDEX \
-DSQLITE_OMIT_SCHEMA_PRAGMAS \
-DSQLITE_OMIT_SCHEMA_VERSION_PRAGMAS \
-DSQLITE_OMIT_SHARED_CACHE \
-DSQLITE_OMIT_TCL_VARIABLE \
-DSQLITE_OMIT_TRACE \
-DSQLITE_OMIT_TRIGGER \
-DSQLITE_OMIT_UTF16"
# SQLITE_OMIT_ATTACH To solve missing sqlite3DbIsNamed symbol
# SQLITE_OMIT_AUTOMATIC_INDEX
# SQLITE_OMIT_AUTORESET
# SQLITE_OMIT_AUTOVACUUM
# SQLITE_OMIT_BETWEEN_OPTIMIZATION
# SQLITE_OMIT_CAST
# SQLITE_OMIT_CTE
# SQLITE_OMIT_DATETIME_FUNCS To solve missing field 'u' initializer
# SQLITE_OMIT_FLOATING_POINT Not needed?
# SQLITE_OMIT_HEX_INTEGER
# SQLITE_OMIT_LIKE_OPTIMIZATION
# SQLITE_OMIT_LOOKASIDE
# SQLITE_OMIT_OR_OPTIMIZATION
# SQLITE_OMIT_PAGER_PRAGMAS To solve missing sqlite3BtreeSetPagerFlags symbol
# SQLITE_OMIT_PRAGMA
# SQLITE_OMIT_QUICKBALANCE
# SQLITE_OMIT_SEH
# SQLITE_OMIT_SUBQUERY
# SQLITE_OMIT_TEMPDB
# SQLITE_OMIT_TRUNCATE_OPTIMIZATION
# SQLITE_OMIT_VACUUM To solve missing sqlite3PagerClearCache symbol
# SQLITE_OMIT_VIEW
# SQLITE_OMIT_VIRTUALTABLE
# SQLITE_OMIT_WAL
# SQLITE_OMIT_WINDOWFUNC
# SQLITE_OMIT_WSD
# SQLITE_OMIT_XFER_OPT
# SQLITE_UNTESTABLE
# SQLITE_ZERO_MALLOC
make sqlite3.c OPTS="$OPTS"

mv sqlite3.c ../../../src/sqlite3/sqlite3.c
mv sqlite3.h ../../../src/sqlite3/sqlite3.h
cp ext/wasm/api/sqlite3-wasm.c ../../../src/sqlite3/sqlite3-wasm.c
