/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

import { writeFile } from 'fs/promises';
import { resolve } from 'path';
import { getFileLicense } from '../license';
import { iLog } from '../log';
import { getUnicodeTableData, UnicodeTableData } from '../unicode-data-store';
import { generateBlocks } from './unicode-data/blocks';
import { generateCaseFoldMappings, generateCaseFoldSimpleMappings, generateSimpleCaseMappings, generateSpecialCaseMappings } from './unicode-data/case';
import { generateCollationContractions, generateCollationEntries, generateCollationImplicitRanges } from './unicode-data/collation';
import { generateDecompositionAndCompositionTables } from './unicode-data/composition';
import { generateConfusables } from './unicode-data/confusable';
import { generateEmoji } from './unicode-data/emoji';
import { generateNCharacters } from './unicode-data/n-characters';
import { generateNames } from './unicode-data/names';
import { generateNumericValues } from './unicode-data/numeric';
import { generateProperties } from './unicode-data/properties';
import { generateScriptExtensions } from './unicode-data/script-extensions';

// Writes the generated Unicode C tables from the in-memory generation data.
export async function generateUnicodeDataHeader(data: UnicodeTableData = getUnicodeTableData()) {
  iLog('Generate Unicode tables');

  const outputPath = resolve(__dirname, '../../../src/unicode-data.h');
  const output = `${getFileLicense()}

// This file is automatically generated. Do not edit.
// clang-format off

#include <stddef.h>
#include <string.h>

#include "unicode-tables.h"

${generateBlocks(data.blocks)}
${generateNames(data.prefixes, data.names)}
${generateEmoji(data.emoji, data.emojiSequences)}
${generateProperties(data.properties)}
${generateScriptExtensions(data.scriptExtensions)}
${generateNCharacters(data.nCharacters)}
${generateDecompositionAndCompositionTables(data.decompositions,
  data.compatibilityDecompositions, data.compositions)}
${generateNumericValues(data.numericValues)}
${generateSimpleCaseMappings(data.simpleCaseMappings)}
${generateSpecialCaseMappings(data.specialCaseMappings)}
${generateCaseFoldMappings(data.caseFoldMappings)}
${generateCaseFoldSimpleMappings(data.caseFoldSimpleMappings)}
${generateConfusables(data.confusables)}
${generateCollationImplicitRanges(data.collationImplicitRanges)}
${generateCollationEntries(data.collationEntries)}
${generateCollationContractions(data.collationContractions)}// clang-format on
`;

  await writeFile(outputPath, output);
}
