/**
 * The Mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 */

#pragma once

#ifndef MJB_LOCALES_H
#define MJB_LOCALES_H

// This file is automatically generated. Do not edit.

/**
 * ISO-639-2 locales
 * See https://www.loc.gov/standards/iso639-2/ for more information.
 */
typedef enum mjb_locale {
    MJB_LOCALE_AA, // Afar
    MJB_LOCALE_AB, // Abkhazian
    MJB_LOCALE_AF, // Afrikaans
    MJB_LOCALE_AK, // Akan
    MJB_LOCALE_SQ, // Albanian
    MJB_LOCALE_AM, // Amharic
    MJB_LOCALE_AR, // Arabic
    MJB_LOCALE_AN, // Aragonese
    MJB_LOCALE_HY, // Armenian
    MJB_LOCALE_AS, // Assamese
    MJB_LOCALE_AV, // Avaric
    MJB_LOCALE_AE, // Avestan
    MJB_LOCALE_AY, // Aymara
    MJB_LOCALE_AZ, // Azerbaijani
    MJB_LOCALE_BA, // Bashkir
    MJB_LOCALE_BM, // Bambara
    MJB_LOCALE_EU, // Basque
    MJB_LOCALE_BE, // Belarusian
    MJB_LOCALE_BN, // Bengali
    MJB_LOCALE_BI, // Bislama
    MJB_LOCALE_BS, // Bosnian
    MJB_LOCALE_BR, // Breton
    MJB_LOCALE_BG, // Bulgarian
    MJB_LOCALE_MY, // Burmese
    MJB_LOCALE_CA, // Catalan; Valencian
    MJB_LOCALE_CH, // Chamorro
    MJB_LOCALE_CE, // Chechen
    MJB_LOCALE_ZH, // Chinese
    MJB_LOCALE_CU, // Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic
    MJB_LOCALE_CV, // Chuvash
    MJB_LOCALE_KW, // Cornish
    MJB_LOCALE_CO, // Corsican
    MJB_LOCALE_CR, // Cree
    MJB_LOCALE_CS, // Czech
    MJB_LOCALE_DA, // Danish
    MJB_LOCALE_DV, // Divehi; Dhivehi; Maldivian
    MJB_LOCALE_NL, // Dutch; Flemish
    MJB_LOCALE_DZ, // Dzongkha
    MJB_LOCALE_EN, // English
    MJB_LOCALE_EO, // Esperanto
    MJB_LOCALE_ET, // Estonian
    MJB_LOCALE_EE, // Ewe
    MJB_LOCALE_FO, // Faroese
    MJB_LOCALE_FJ, // Fijian
    MJB_LOCALE_FI, // Finnish
    MJB_LOCALE_FR, // French
    MJB_LOCALE_FY, // Western Frisian
    MJB_LOCALE_FF, // Fulah
    MJB_LOCALE_KA, // Georgian
    MJB_LOCALE_DE, // German
    MJB_LOCALE_GD, // Gaelic; Scottish Gaelic
    MJB_LOCALE_GA, // Irish
    MJB_LOCALE_GL, // Galician
    MJB_LOCALE_GV, // Manx
    MJB_LOCALE_EL, // Greek, Modern (1453-)
    MJB_LOCALE_GN, // Guarani
    MJB_LOCALE_GU, // Gujarati
    MJB_LOCALE_HT, // Haitian; Haitian Creole
    MJB_LOCALE_HA, // Hausa
    MJB_LOCALE_HE, // Hebrew
    MJB_LOCALE_HZ, // Herero
    MJB_LOCALE_HI, // Hindi
    MJB_LOCALE_HO, // Hiri Motu
    MJB_LOCALE_HR, // Croatian
    MJB_LOCALE_HU, // Hungarian
    MJB_LOCALE_IG, // Igbo
    MJB_LOCALE_IS, // Icelandic
    MJB_LOCALE_IO, // Ido
    MJB_LOCALE_II, // Sichuan Yi; Nuosu
    MJB_LOCALE_IU, // Inuktitut
    MJB_LOCALE_IE, // Interlingue; Occidental
    MJB_LOCALE_IA, // Interlingua (International Auxiliary Language Association)
    MJB_LOCALE_ID, // Indonesian
    MJB_LOCALE_IK, // Inupiaq
    MJB_LOCALE_IT, // Italian
    MJB_LOCALE_JV, // Javanese
    MJB_LOCALE_JA, // Japanese
    MJB_LOCALE_KL, // Kalaallisut; Greenlandic
    MJB_LOCALE_KN, // Kannada
    MJB_LOCALE_KS, // Kashmiri
    MJB_LOCALE_KR, // Kanuri
    MJB_LOCALE_KK, // Kazakh
    MJB_LOCALE_KM, // Central Khmer
    MJB_LOCALE_KI, // Kikuyu; Gikuyu
    MJB_LOCALE_RW, // Kinyarwanda
    MJB_LOCALE_KY, // Kirghiz; Kyrgyz
    MJB_LOCALE_KV, // Komi
    MJB_LOCALE_KG, // Kongo
    MJB_LOCALE_KO, // Korean
    MJB_LOCALE_KJ, // Kuanyama; Kwanyama
    MJB_LOCALE_KU, // Kurdish
    MJB_LOCALE_LO, // Lao
    MJB_LOCALE_LA, // Latin
    MJB_LOCALE_LV, // Latvian
    MJB_LOCALE_LI, // Limburgan; Limburger; Limburgish
    MJB_LOCALE_LN, // Lingala
    MJB_LOCALE_LT, // Lithuanian
    MJB_LOCALE_LB, // Luxembourgish; Letzeburgesch
    MJB_LOCALE_LU, // Luba-Katanga
    MJB_LOCALE_LG, // Ganda
    MJB_LOCALE_MK, // Macedonian
    MJB_LOCALE_MH, // Marshallese
    MJB_LOCALE_ML, // Malayalam
    MJB_LOCALE_MI, // Maori
    MJB_LOCALE_MR, // Marathi
    MJB_LOCALE_MS, // Malay
    MJB_LOCALE_MG, // Malagasy
    MJB_LOCALE_MT, // Maltese
    MJB_LOCALE_MN, // Mongolian
    MJB_LOCALE_NA, // Nauru
    MJB_LOCALE_NV, // Navajo; Navaho
    MJB_LOCALE_NR, // Ndebele, South; South Ndebele
    MJB_LOCALE_ND, // Ndebele, North; North Ndebele
    MJB_LOCALE_NG, // Ndonga
    MJB_LOCALE_NE, // Nepali
    MJB_LOCALE_NN, // Norwegian Nynorsk; Nynorsk, Norwegian
    MJB_LOCALE_NB, // Bokmål, Norwegian; Norwegian Bokmål
    MJB_LOCALE_NO, // Norwegian
    MJB_LOCALE_NY, // Chichewa; Chewa; Nyanja
    MJB_LOCALE_OC, // Occitan (post 1500)
    MJB_LOCALE_OJ, // Ojibwa
    MJB_LOCALE_OR, // Oriya
    MJB_LOCALE_OM, // Oromo
    MJB_LOCALE_OS, // Ossetian; Ossetic
    MJB_LOCALE_PA, // Panjabi; Punjabi
    MJB_LOCALE_FA, // Persian
    MJB_LOCALE_PI, // Pali
    MJB_LOCALE_PL, // Polish
    MJB_LOCALE_PT, // Portuguese
    MJB_LOCALE_PS, // Pushto; Pashto
    MJB_LOCALE_QU, // Quechua
    MJB_LOCALE_RM, // Romansh
    MJB_LOCALE_RO, // Romanian; Moldavian; Moldovan
    MJB_LOCALE_RN, // Rundi
    MJB_LOCALE_RU, // Russian
    MJB_LOCALE_SG, // Sango
    MJB_LOCALE_SA, // Sanskrit
    MJB_LOCALE_SI, // Sinhala; Sinhalese
    MJB_LOCALE_SK, // Slovak
    MJB_LOCALE_SL, // Slovenian
    MJB_LOCALE_SE, // Northern Sami
    MJB_LOCALE_SM, // Samoan
    MJB_LOCALE_SN, // Shona
    MJB_LOCALE_SD, // Sindhi
    MJB_LOCALE_SO, // Somali
    MJB_LOCALE_ST, // Sotho, Southern
    MJB_LOCALE_ES, // Spanish; Castilian
    MJB_LOCALE_SC, // Sardinian
    MJB_LOCALE_SR, // Serbian
    MJB_LOCALE_SS, // Swati
    MJB_LOCALE_SU, // Sundanese
    MJB_LOCALE_SW, // Swahili
    MJB_LOCALE_SV, // Swedish
    MJB_LOCALE_TY, // Tahitian
    MJB_LOCALE_TA, // Tamil
    MJB_LOCALE_TT, // Tatar
    MJB_LOCALE_TE, // Telugu
    MJB_LOCALE_TG, // Tajik
    MJB_LOCALE_TL, // Tagalog
    MJB_LOCALE_TH, // Thai
    MJB_LOCALE_BO, // Tibetan
    MJB_LOCALE_TI, // Tigrinya
    MJB_LOCALE_TO, // Tonga (Tonga Islands)
    MJB_LOCALE_TN, // Tswana
    MJB_LOCALE_TS, // Tsonga
    MJB_LOCALE_TK, // Turkmen
    MJB_LOCALE_TR, // Turkish
    MJB_LOCALE_TW, // Twi
    MJB_LOCALE_UG, // Uighur; Uyghur
    MJB_LOCALE_UK, // Ukrainian
    MJB_LOCALE_UR, // Urdu
    MJB_LOCALE_UZ, // Uzbek
    MJB_LOCALE_VE, // Venda
    MJB_LOCALE_VI, // Vietnamese
    MJB_LOCALE_VO, // Volapük
    MJB_LOCALE_CY, // Welsh
    MJB_LOCALE_WA, // Walloon
    MJB_LOCALE_WO, // Wolof
    MJB_LOCALE_XH, // Xhosa
    MJB_LOCALE_YI, // Yiddish
    MJB_LOCALE_YO, // Yoruba
    MJB_LOCALE_ZA, // Zhuang; Chuang
    MJB_LOCALE_ZU  // Zulu
} mjb_locale;

#endif // MJB_LOCALES_H
