/**
 * The mojibake library
 *
 * This file is distributed under the MIT License. See LICENSE for details.
 *
 * This code is autogenerated do not modify
 */

#ifndef MB_UNICODE_DATA_H
#define MB_UNICODE_DATA_H

#include "mojibake.h"

#define MB_CHARACTER_MAX 33797

extern mb_character mb_characters[MB_CHARACTER_MAX];

#endif /* MB_UNICODE_DATA_H */
